on:
  push:
    tags:

jobs:
  build_translation:
    runs-on: ubuntu-latest
    steps:
      - name: check out repository
        uses: actions/checkout@v3
      - name: set version
        run:
          echo "VERSION=$(git describe --tags)" >> $GITHUB_ENV
      - name: create dist
        run:
          bash build.sh ${{ env.VERSION }}
      - name: workshop upload
        uses: ./.github/actions/workshop-upload
        with:
          appId: '1612770'
          itemId: '2951508329'
          contentPath: 'dist'
          changelog: 'https://github.com/meeuw/sweet-transit-community-translations/releases/tag/${{ env.VERSION }}'
        env:
          STEAM_USERNAME: ${{ secrets.STEAM_USERNAME }}
          STEAM_MTBF: ${{ secrets.STEAM_MTBF }}
          STEAM_CONNECT_CACHE_1: ${{ secrets.STEAM_CONNECT_CACHE_1 }}
          STEAM_CONNECT_CACHE_2: ${{ secrets.STEAM_CONNECT_CACHE_2 }}
          STEAM_ID: ${{ secrets.STEAM_ID }}
